<?php

// Interface generated by https://github.com/ewth/interface-generator
// Do not use without reviewing first!

interface CardDetailsInterface
{

    /**
     * @return string
     */
    public function getSomebodyName();

    /**
     * @param string $somebodyName
     *
     * @return $this
     */
    public function setSomebodyName(string $somebodyName);

    /**
     * @return string
     */
    public function getNumber();

    /**
     * @param string $number
     *
     * @return $this
     */
    public function setNumber(string $number);

    /**
     * @return string
     */
    public function getExpiryMonth();

    /**
     * @param string $expiryMonth
     *
     * @return $this
     */
    public function setExpiryMonth(string $expiryMonth);

    /**
     * @return string
     */
    public function getExpiryYear();

    /**
     * @param string $expiryYear
     *
     * @return $this
     */
    public function setExpiryYear(string $expiryYear);

    /**
     * @return string
     */
    public function getStartMonth();

    /**
     * @param string $startMonth
     *
     * @return $this
     */
    public function setStartMonth(string $startMonth);

    /**
     * @return string
     */
    public function getStartYear();

    /**
     * @param string $startYear
     *
     * @return $this
     */
    public function setStartYear(string $startYear);

    /**
     * @return string
     */
    public function getIssueNumber();

    /**
     * @param string $issueNumber
     *
     * @return $this
     */
    public function setIssueNumber(string $issueNumber);

    /**
     * @return string
     */
    public function getCvn();

    /**
     * @param string $cvn
     *
     * @return $this
     */
    public function setCvn(string $cvn);

}
