<?php

// Class generated by https://github.com/ewth/interface-generator
// Do not use without reviewing first!

class CardDetails implements CardDetailsInterface
{


    /** @var string $name */
    protected $name;
    
    /** @var string $number */
    protected $number;
    
    /** @var string $expiryMonth */
    protected $expiryMonth;
    
    /** @var string $expiryYear */
    protected $expiryYear;
    
    /** @var string $startMonth */
    protected $startMonth;
    
    /** @var string $startYear */
    protected $startYear;
    
    /** @var string $issueNumber */
    protected $issueNumber;
    
    /** @var string $cvn */
    protected $cvn;

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     *
     * @return $this
     */
    public function setName(string $name): CardDetailsInterface
    {
        $this->name = $name;
        
        return $this;
    }

    /**
     * @return string
     */
    public function getNumber(): string
    {
        return $this->number;
    }

    /**
     * @param string $number
     *
     * @return $this
     */
    public function setNumber(string $number): CardDetailsInterface
    {
        $this->number = $number;
        
        return $this;
    }

    /**
     * @return string
     */
    public function getExpiryMonth(): string
    {
        return $this->expiryMonth;
    }

    /**
     * @param string $expiryMonth
     *
     * @return $this
     */
    public function setExpiryMonth(string $expiryMonth): CardDetailsInterface
    {
        $this->expiryMonth = $expiryMonth;
        
        return $this;
    }

    /**
     * @return string
     */
    public function getExpiryYear(): string
    {
        return $this->expiryYear;
    }

    /**
     * @param string $expiryYear
     *
     * @return $this
     */
    public function setExpiryYear(string $expiryYear): CardDetailsInterface
    {
        $this->expiryYear = $expiryYear;
        
        return $this;
    }

    /**
     * @return string
     */
    public function getStartMonth(): string
    {
        return $this->startMonth;
    }

    /**
     * @param string $startMonth
     *
     * @return $this
     */
    public function setStartMonth(string $startMonth): CardDetailsInterface
    {
        $this->startMonth = $startMonth;
        
        return $this;
    }

    /**
     * @return string
     */
    public function getStartYear(): string
    {
        return $this->startYear;
    }

    /**
     * @param string $startYear
     *
     * @return $this
     */
    public function setStartYear(string $startYear): CardDetailsInterface
    {
        $this->startYear = $startYear;
        
        return $this;
    }

    /**
     * @return string
     */
    public function getIssueNumber(): string
    {
        return $this->issueNumber;
    }

    /**
     * @param string $issueNumber
     *
     * @return $this
     */
    public function setIssueNumber(string $issueNumber): CardDetailsInterface
    {
        $this->issueNumber = $issueNumber;
        
        return $this;
    }

    /**
     * @return string
     */
    public function getCvn(): string
    {
        return $this->cvn;
    }

    /**
     * @param string $cvn
     *
     * @return $this
     */
    public function setCvn(string $cvn): CardDetailsInterface
    {
        $this->cvn = $cvn;
        
        return $this;
    }

}
